all:
	g++ -fopenmp bbs.cpp -o bbs # serial bubble sort
	g++ -fopenmp bbp.cpp -o bbp # parallel bubble sort
	g++ -fopenmp qss.cpp -o qss # serial quick sort
	g++ -fopenmp qsp.cpp -o qsp # parallel quick sort
	g++ -fopenmp mss.cpp -o mss # serial merge sort
	g++ -fopenmp msp.cpp -o msp # parallel merge sort
	g++ -fopenmp reference.cpp -o reference # STL sort (cstdlib)
